# Generated by Django 2.2.5 on 2019-10-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EM_Category',
            fields=[
                ('CategoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
    ]
