# Generated by Django 2.2.5 on 2019-10-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('attachment_id', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('is_active', models.FileField(upload_to='')),
                ('parent_email_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('create_date', models.DateTimeField()),
                ('is_active', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EmReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.FileField(upload_to='')),
                ('is_starred', models.FileField(upload_to='')),
                ('is_active', models.FileField(upload_to='')),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.EmEmail')),
            ],
        ),
        migrations.CreateModel(
            name='EmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_mail', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('is_active', models.FileField(upload_to='')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.EmGroup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.EmUser')),
            ],
        ),
        migrations.CreateModel(
            name='GnGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=10, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_node', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('voice', models.FileField(null=True, upload_to='')),
                ('face', models.FileField(null=True, upload_to='')),
                ('salt', models.IntegerField()),
                ('pin', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='EM_Category',
        ),
        migrations.AddField(
            model_name='emreceiver',
            name='user_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.EmUserGroup'),
        ),
        migrations.AddField(
            model_name='emreceiver',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.ScUser'),
        ),
        migrations.AddField(
            model_name='emgroup',
            name='group_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.GnGroupType'),
        ),
        migrations.AddField(
            model_name='ememail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.EmUser'),
        ),
    ]
